import { useEffect } from 'react';
import { ScrollArea } from "@/components/ui/scroll-area";

const TwitterThreadsGrid = () => {
  useEffect(() => {
    // Load Twitter widgets script
    const script = document.createElement("script");
    script.src = "https://platform.twitter.com/widgets.js";
    script.async = true;
    document.body.appendChild(script);

    return () => {
      document.body.removeChild(script);
    };
  }, []);

  const threadsGrid = [
    [
      `<blockquote class="twitter-tweet"><p lang="en" dir="ltr">🧵Thread <a href="https://twitter.com/MyriadMarkets?ref_src=twsrc%5Etfw">@MyriadMarkets</a> x <a href="https://twitter.com/RugRadio?ref_src=twsrc%5Etfw">@RugRadio</a><br><br>My DMs are full of people asking what is going on with Myriad Market and the Rug Radio Genesis NFTs, <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a>, <a href="https://twitter.com/search?q=%24MYR&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$MYR</a>, etc...<br><br>All details below 👇</p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942675990004006?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
      `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">1/ DASTAN is the parent company of Rug Radio, Decrypt, Myriad,Lucky Trader, Degenz.<a href="https://twitter.com/MyriadMarkets?ref_src=twsrc%5Etfw">@MyriadMarkets</a> is the new platform of the DASTAN ecosystem that integrates onchain predictions Markets and content consuming.<a href="https://t.co/jGWHJMTyf3">https://t.co/jGWHJMTyf3</a></p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942678871450023?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
      `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">2/ Myriad Foundation announced a few days ago that <a href="https://twitter.com/search?q=%24MYR&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$MYR</a> token will be the one that bridges media, predictions and digital advertising.<br><br>The <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> Holders and Rug Genesis NFT holders will get 25.5% of the <a href="https://twitter.com/search?q=%24MYR&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$MYR</a> drop.<br><br>Check this post:<a href="https://t.co/tUywAWqtfS">https://t.co/tUywAWqtfS</a></p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942681807483155?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
      `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">3/ The <a href="https://twitter.com/search?q=%24MYR&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$MYR</a> token will be launched on <a href="https://twitter.com/AbstractChain?ref_src=twsrc%5Etfw">@AbstractChain</a> <br><br>What is Abstract?<br>Abstract is both the platform and blockchain powering the next generation of consumer crypto. Abstract is a part of Igloo Inc, the parent company of PudgyPenguins. ABS mainnet will launch in 2025 and MYRIAD…</p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942685200396467?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
      `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">4/ What is <a href="https://twitter.com/search?q=%24MYR&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$MYR</a>?<br><br>It is the new token to be launched by the Myriad Foundation in Q1. <a href="https://twitter.com/search?q=%24MYR&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$MYR</a> will fuel the Myriad protocol and be more broadly at the center of the Dastan ecosystem.</p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942688166055972?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
      `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">5/ What is <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a>?<br><br>It launched in 2022 as the token emitted by the Rug Radio Genesis NFT which is one of the initial NFT collection of the Rug Radio ecosystem.<br><br>They are 3 &quot;level&quot; of Rug Genesis:<br>- Standard<br>- Scarce 1 &amp; Scarce 2<br>- Rare 1 &amp; Rare 2<br><br>Everything start with <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a>, which… <a href="https://t.co/shH2cDiBK4">pic.twitter.com/shH2cDiBK4</a></p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942691999670379?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
      `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">6/ How does <a href="https://twitter.com/search?q=%24MYR&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$MYR</a> relates to <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a>?<br><br>There will be a conversion process that will be announced by the Myriad Foundation before the <a href="https://twitter.com/search?q=%24MYR&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$MYR</a> token is generated. The MYRIAD Foundation has confirmed that Rug Radio Genesis / <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> holders will receive 25.5% of the total <a href="https://twitter.com/search?q=%24MYR&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$MYR</a> supply as a…</p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942695589974119?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
      `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">7/ How do the <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> yield work?<a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> has been yielding and hold natively on the NFTs and there is no need to claim it NOW.<br><br>Whether you are holding your Genesis NFT, <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> token, there is no need to move,claim or convert anything at this time until The Myriad Foundation releases…</p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942698387395025?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
      `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">The yield process began on 11th January 2022 for 5 years.<br><br>So, here we go with the math:<br><br>- Standard Rug Genesis, yield 5 <a href="https://twitter.com/search?q=%24rug&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$rug</a> token per day<br>- Scarce 1 &amp; Scarce 2, yield 7 <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> token per day<br>- Rare 1 &amp; Rare 2, yield 11 <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> token yield per day</p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942701210349931?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
      `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">8/ Regarding the timeline, we have 2 years left of yielding so around 740 days left:<br><br>- A standard Genesis NFT will still yield 3700 <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a><br>- A scarce 1 &amp; 2 still yield will 5180 <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a><br>- A rare 1 &amp; 2 still yield will 8140 <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a></p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942704033177781?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
      `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">As 3 years are already gone, you could see (if <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> token haven't been claimed):<br><br>- A standard Genesis NFT should have emitted 5475 <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a><br>- A scarce 1 &amp; 2 should have emitted 7665 <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a><br>- A rare 1 &amp; 2 should have emitted 12045 <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a></p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942706897825951?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
      `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">9/ So how can you check the <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> claimed or unclaimed?<br><br>Go to this website <a href="https://t.co/BOnlxGQye7">https://t.co/BOnlxGQye7</a> and check with the NFT ID</p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942709947134231?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
      `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">10/ How to understand &quot;claimed or unclaimed <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a>&quot;?<br><br>If the Genesis NFT you are looking to buy display &quot;0&quot; in the column called Available to claim, it means the previous owner claimed the <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> token yielded but you will still get the future yielded <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> tokens as mentioned in the… <a href="https://t.co/0GnUugbbs2">pic.twitter.com/0GnUugbbs2</a></p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942713625227301?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
      `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">If the Genesis NFT you are looking to buy display &quot;xxxx&quot; in the column called Available to claim, it means the previous owner didn&#39;t claimed the yielded <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> tokens associated to the NFT and you will still get the future yielded <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> tokens as mentioned in the part 7/ and 8/. <a href="https://t.co/lcRwkFoNM9">pic.twitter.com/lcRwkFoNM9</a></p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942717387833463?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
      `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">11/ <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> token on Uniswap<br><br>You can also find the <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> token on Uniswap with the CA below:<br><br>0xd2d8d78087d0e43bc4804b6f946674b2ee406b80<br><br>Be aware there is very low liquidity in the pool, so it&#39;s not easy to buy <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> token. Afterall, it&#39;s also a way to buy RUG token directly and not…</p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942720814297547?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
      `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">13/ How do I earn points?<br><br>Firstly, you can complete quests on the media ecosystem of DASTAN which includes to read articles on Decrypt, listen to FOMO Hour X space, Watch youtube interview by Farokh, X/Twitter quests, etc...<br><br>You can also participate in NFT community quests like… <a href="https://t.co/93GkW9gTfU">pic.twitter.com/93GkW9gTfU</a></p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942727437046141?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`
    ],
    `<blockquote class="twitter-tweet"><p lang="en" dir="ltr">MYRIAD Points are the foundation of the MYRIAD ecosystem.<br><br>Here&#39;s everything you need to know about MYRIAD Points 🧵 <a href="https://t.co/Hs8Gy7Iqrm">pic.twitter.com/Hs8Gy7Iqrm</a></p>&mdash; MYRIAD (@MyriadMarkets) <a href="https://twitter.com/MyriadMarkets/status/1747664131664339087?ref_src=twsrc%5Etfw">January 17, 2024</a></blockquote>`
  ];

  return (
    <div className="py-24 bg-black">
      <div className="container mx-auto">
        <div className="text-center mb-12">
          <h2 className="text-4xl font-bold text-white mb-4">What People Are Saying</h2>
          <p className="text-lg text-gray-300">
            Join the conversation about MYRIAD
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {/* First column with scrollable thread */}
          <ScrollArea className="h-[600px] md:h-[700px] w-full rounded-md bg-white/80">
            <div className="space-y-4 p-2">
              {Array.isArray(threadsGrid[0]) && threadsGrid[0].map((tweet, index) => (
                <div key={index} className="w-full" dangerouslySetInnerHTML={{ __html: tweet }} />
              ))}
            </div>
          </ScrollArea>

          {/* Second column with single tweet */}
          <ScrollArea className="h-[600px] md:h-[700px] w-full rounded-md bg-white/80">
            <div className="p-2" dangerouslySetInnerHTML={{ __html: threadsGrid[1] }} />
          </ScrollArea>
        </div>
      </div>
    </div>
  );
};

export default TwitterThreadsGrid;