import { memo } from 'react';
import TwitterAuthorLink from './twitter/TwitterAuthorLink';
import TwitterThreadColumn from './twitter/TwitterThreadColumn';

const threadsGrid = [
  [
    `<blockquote class="twitter-tweet"><p lang="en" dir="ltr">🧵Thread <a href="https://twitter.com/MyriadMarkets?ref_src=twsrc%5Etfw">@MyriadMarkets</a> x <a href="https://twitter.com/RugRadio?ref_src=twsrc%5Etfw">@RugRadio</a><br><br>My DMs are full of people asking what is going on with Myriad Market and the Rug Radio Genesis NFTs, <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a>, <a href="https://twitter.com/search?q=%24MYR&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$MYR</a>, etc...<br><br>All details below 👇</p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942675990004006?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">1/ DASTAN is the parent company of Rug Radio, Decrypt, Myriad,Lucky Trader, Degenz.<a href="https://twitter.com/MyriadMarkets?ref_src=twsrc%5Etfw">@MyriadMarkets</a> is the new platform of the DASTAN ecosystem that integrates onchain predictions Markets and content consuming.<a href="https://t.co/jGWHJMTyf3">https://t.co/jGWHJMTyf3</a></p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942678871450023?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">2/ Myriad Foundation announced a few days ago that <a href="https://twitter.com/search?q=%24MYR&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$MYR</a> token will be the one that bridges media, predictions and digital advertising.<br><br>The <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> Holders and Rug Genesis NFT holders will get 25.5% of the <a href="https://twitter.com/search?q=%24MYR&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$MYR</a> drop.<br><br>Check this post:<a href="https://t.co/tUywAWqtfS">https://t.co/tUywAWqtfS</a></p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942681807483155?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">3/ The <a href="https://twitter.com/search?q=%24MYR&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$MYR</a> token will be launched on <a href="https://twitter.com/AbstractChain?ref_src=twsrc%5Etfw">@AbstractChain</a> <br><br>What is Abstract?<br>Abstract is both the platform and blockchain powering the next generation of consumer crypto. Abstract is a part of Igloo Inc, the parent company of PudgyPenguins. ABS mainnet will launch in 2025 and MYRIAD…</p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942685200396467?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">4/ What is <a href="https://twitter.com/search?q=%24MYR&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$MYR</a>?<br><br>It is the new token to be launched by the Myriad Foundation in Q1. <a href="https://twitter.com/search?q=%24MYR&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$MYR</a> will fuel the Myriad protocol and be more broadly at the center of the Dastan ecosystem.</p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942688166055972?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">5/ What is <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a>?<br><br>It launched in 2022 as the token emitted by the Rug Radio Genesis NFT which is one of the initial NFT collection of the Rug Radio ecosystem.<br><br>They are 3 &quot;level&quot; of Rug Genesis:<br>- Standard<br>- Scarce 1 &amp; Scarce 2<br>- Rare 1 &amp; Rare 2<br><br>Everything start with <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a>, which… <a href="https://t.co/shH2cDiBK4">pic.twitter.com/shH2cDiBK4</a></p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942691999670379?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">6/ How does <a href="https://twitter.com/search?q=%24MYR&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$MYR</a> relates to <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a>?<br><br>There will be a conversion process that will be announced by the Myriad Foundation before the <a href="https://twitter.com/search?q=%24MYR&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$MYR</a> token is generated. The MYRIAD Foundation has confirmed that Rug Radio Genesis / <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> holders will receive 25.5% of the total <a href="https://twitter.com/search?q=%24MYR&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$MYR</a> supply as a…</p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942695589974119?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">7/ How do the <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> yield work?<a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> has been yielding and hold natively on the NFTs and there is no need to claim it NOW.<br><br>Whether you are holding your Genesis NFT, <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> token, there is no need to move,claim or convert anything at this time until The Myriad Foundation releases…</p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942698387395025?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">The yield process began on 11th January 2022 for 5 years.<br><br>So, here we go with the math:<br><br>- Standard Rug Genesis, yield 5 <a href="https://twitter.com/search?q=%24rug&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$rug</a> token per day<br>- Scarce 1 &amp; Scarce 2, yield 7 <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> token per day<br>- Rare 1 &amp; Rare 2, yield 11 <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> token yield per day</p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942701210349931?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">8/ Regarding the timeline, we have 2 years left of yielding so around 740 days left:<br><br>- A standard Genesis NFT will still yield 3700 <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a><br>- A scarce 1 &amp; 2 still yield will 5180 <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a><br>- A rare 1 &amp; 2 still yield will 8140 <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a></p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942704033177781?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">As 3 years are already gone, you could see (if <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> token haven't been claimed):<br><br>- A standard Genesis NFT should have emitted 5475 <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a><br>- A scarce 1 &amp; 2 should have emitted 7665 <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a><br>- A rare 1 &amp; 2 should have emitted 12045 <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a></p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942706897825951?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">9/ So how can you check the <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> claimed or unclaimed?<br><br>Go to this website <a href="https://t.co/BOnlxGQye7">https://t.co/BOnlxGQye7</a> and check with the NFT ID</p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942713625227301?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">If the Genesis NFT you are looking to buy display &quot;0&quot; in the column called Available to claim, it means the previous owner claimed the <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> token yielded but you will still get the future yielded <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> tokens as mentioned in the… <a href="https://t.co/0GnUugbbs2">pic.twitter.com/0GnUugbbs2</a></p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942717387833463?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">If the Genesis NFT you are looking to buy display &quot;xxxx&quot; in the column called Available to claim, it means the previous owner didn&#39;t claimed the yielded <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> tokens associated to the NFT and you will still get the future yielded <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> tokens as mentioned in the part 7/ and 8/. <a href="https://t.co/lcRwkFoNM9">pic.twitter.com/lcRwkFoNM9</a></p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942717387833463?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">11/ <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> token on Uniswap<br><br>You can also find the <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> token on Uniswap with the CA below:<br><br>0xd2d8d78087d0e43bc4804b6f946674b2ee406b80<br><br>Be aware there is very low liquidity in the pool, so it&#39;s not easy to buy <a href="https://twitter.com/search?q=%24RUG&amp;src=ctag&amp;ref_src=twsrc%5Etfw">$RUG</a> token. Afterall, it&#39;s also a way to buy RUG token directly and not…</p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942720814297547?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">13/ How do I earn points?<br><br>Firstly, you can complete quests on the media ecosystem of DASTAN which includes to read articles on Decrypt, listen to FOMO Hour X space, Watch youtube interview by Farokh, X/Twitter quests, etc...<br><br>You can also participate in NFT community quests like… <a href="https://t.co/93GkW9gTfU">pic.twitter.com/93GkW9gTfU</a></p>&mdash; ※ Vince (@vincevanbtc) <a href="https://twitter.com/vincevanbtc/status/1874942727437046141?ref_src=twsrc%5Etfw">January 2, 2025</a></blockquote>`
  ] as const,
  [
    `<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Many are touting <a href="https://twitter.com/MyriadMarkets?ref_src=twsrc%5Etfw">@MyriadMarkets</a> as the next big thing in 2025.<br><br>The emerging prediction markets platform is quickly capturing mindshare, with its gamified approach to predictions, embrace of the web3 and integration into news and social media.<br><br>But really, why such a big deal?👇 <a href="https://t.co/RBVWItrDYR">pic.twitter.com/RBVWItrDYR</a></p>&mdash; Tyler DurdΞth (@tylerdurdeth) <a href="https://twitter.com/tylerdurdeth/status/1875887464684159442?ref_src=twsrc%5Etfw">January 5, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">To understand Myriad’s true potential, it is critical to put it into the context of its broader ecosystem. Myriad is a subsidiary of Dastan, a group which owns <a href="https://twitter.com/DecryptMedia?ref_src=twsrc%5Etfw">@DecryptMedia</a>, <a href="https://twitter.com/RugRadio?ref_src=twsrc%5Etfw">@RugRadio</a> and <a href="https://twitter.com/LuckyTraderHQ?ref_src=twsrc%5Etfw">@LuckyTraderHQ</a>.<br><br>All 3 sister companies are essential to what will make Myriad so unique <a href="https://t.co/JsTQQl2WTB">pic.twitter.com/JsTQQl2WTB</a></p>&mdash; Tyler DurdΞth (@tylerdurdeth) <a href="https://twitter.com/tylerdurdeth/status/1875887476910534928?ref_src=twsrc%5Etfw">January 5, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">Decrypt is a top publication in the crypto space with 50m yearly visits. Known for its credibility and high-quality reporting, it is the trusted resource for both seasoned and novice crypto participants globally.<br><br>Think of it as the traditional media branch of the ecosystem. <a href="https://t.co/UqQCQpl59F">pic.twitter.com/UqQCQpl59F</a></p>&mdash; Tyler DurdΞth (@tylerdurdeth) <a href="https://twitter.com/tylerdurdeth/status/1875887510473306304?ref_src=twsrc%5Etfw">January 5, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">To understand how important Decrypt is as a trusted news source, there is no better example that this <a href="https://twitter.com/joerogan?ref_src=twsrc%5Etfw">@joerogan</a> podcast clip, showing Joe Rogan looking for more colour on the Hawk Tuah token debacle <a href="https://t.co/mIL8r1Ci09">https://t.co/mIL8r1Ci09</a></p>&mdash; Tyler DurdΞth (@tylerdurdeth) <a href="https://twitter.com/tylerdurdeth/status/1875887517758840995?ref_src=twsrc%5Etfw">January 5, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">Importantly, it formed an alliance with virtually all the major web3 publications in APAC, giving it even more distribution power in one of the largest crypto markets.<br><br>This will matter immensely once we start looking into how Myriad will leverage the Dastan super network. <a href="https://t.co/DpF3weFPoY">https://t.co/DpF3weFPoY</a></p>&mdash; Tyler DurdΞth (@tylerdurdeth) <a href="https://twitter.com/tylerdurdeth/status/1875887521986662822?ref_src=twsrc%5Etfw">January 5, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">Rug Radio is a multi-media ecosystem that empowers content creators through shared economy, distribution and monetization - generating 100s of millions views on content covering crypto, web3, gaming and other topics.<br><br>Think of it as the “new media” side of the Dastan empire.</p>&mdash; Tyler DurdΞth (@tylerdurdeth) <a href="https://twitter.com/tylerdurdeth/status/1875887528626254196?ref_src=twsrc%5Etfw">January 5, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">Rug Radio’s most notable feat of arms was to bring the first interview with Donal Trump dedicated to the crypto industry. Millions of views across socials and a huge boost to <a href="https://twitter.com/farokh?ref_src=twsrc%5Etfw">@farokh</a> and Rug Radio’s aura within the space. <a href="https://t.co/RN1eVXgLSH">https://t.co/RN1eVXgLSH</a></p>&mdash; Tyler DurdΞth (@tylerdurdeth) <a href="https://twitter.com/tylerdurdeth/status/1875887532581552381?ref_src=twsrc%5Etfw">January 5, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">Rug Radio made strategic acquisitions to expand its sphere of influence and reach, notably with the addition of <a href="https://twitter.com/LuckyTraderHQ?ref_src=twsrc%5Etfw">@LuckyTraderHQ</a> led by the iconic <a href="https://twitter.com/Tyler_Did_It?ref_src=twsrc%5Etfw">@Tyler_Did_It</a><br><br>It is now by far the biggest network of web3 content creators and reaches virtually every corner of the space. <a href="https://t.co/ZafBAzQXDx">https://t.co/ZafBAzQXDx</a></p>&mdash; Tyler DurdΞth (@tylerdurdeth) <a href="https://twitter.com/tylerdurdeth/status/1875887537274949663?ref_src=twsrc%5Etfw">January 5, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">Now back to Myriad. <br><br>Most rebuttals to Myriad’s predicted future dominance in the prediction markets sector revolve around the fact that an already established player, <a href="https://twitter.com/Polymarket?ref_src=twsrc%5Etfw">@Polymarket</a>, has a stronghold on the industry. <br><br>That view point is ignoring 2 critical aspects: <a href="https://t.co/x34ZIvEYHT">pic.twitter.com/x34ZIvEYHT</a></p>&mdash; Tyler DurdΞth (@tylerdurdeth) <a href="https://twitter.com/tylerdurdeth/status/1875887566815404486?ref_src=twsrc%5Etfw">January 5, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">1. Few sectors are structurally favourable to a monopoly. I don’t believe prediction markets is one of them. Polymarket got an edge in being early and having captured trad media attention. However, nothing stops a new player from shaking up the hierarchy with a better product. <a href="https://t.co/BA4GxaySnf">pic.twitter.com/BA4GxaySnf</a></p>&mdash; Tyler DurdΞth (@tylerdurdeth) <a href="https://twitter.com/tylerdurdeth/status/1875887586167894045?ref_src=twsrc%5Etfw">January 5, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">2. Myriad is not just trying to be a better Polymarket, it is going to be a lot more with elements of gamification and socialfi that are clearly missing with Polymarket. As such, it may not only capture some of Polymarket’s market share but also create its own new user base. <a href="https://t.co/ZMrka3ZGDz">pic.twitter.com/ZMrka3ZGDz</a></p>&mdash; Tyler DurdΞth (@tylerdurdeth) <a href="https://twitter.com/tylerdurdeth/status/1875887603809222939?ref_src=twsrc%5Etfw">January 5, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">To understand how, one needs to look at the tech side of the platform. Instead of asking users to come to it, Myriad will come to them thanks to a desktop extension that seamlessly embeds related prediction markets into articles, posts and videos. <a href="https://t.co/SlQYySr9s1">pic.twitter.com/SlQYySr9s1</a></p>&mdash; Tyler DurdΞth (@tylerdurdeth) <a href="https://twitter.com/tylerdurdeth/status/1875887649124442480?ref_src=twsrc%5Etfw">January 5, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">One could even imagine that, in the future, partners media won’t even require an extension to be installed. Prediction markets will be natively integrated into the content with just a Myriad login, broadening even further the user base. <a href="https://t.co/MEHwyKiveN">pic.twitter.com/MEHwyKiveN</a></p>&mdash; Tyler DurdΞth (@tylerdurdeth) <a href="https://twitter.com/tylerdurdeth/status/1875887659626995998?ref_src=twsrc%5Etfw">January 5, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">And this is where the Dastan ecosystem is such a massive edge for Myriad, and also a giant moat to its competitors. With its unparalleled network of media outlets, Myriad is going to be pushed to millions of content consumers across dozens of content sources. X, YT, news sites…</p>&mdash; Tyler DurdΞth (@tylerdurdeth) <a href="https://twitter.com/tylerdurdeth/status/1875887663045398643?ref_src=twsrc%5Etfw">January 5, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">Importantly, it will serve a very useful purpose to its media sister companies and partners (remember the APAC alliance?). While many associate prediction markets with gambling, it is true “raison d’être” is to be an alternative source of truth<br><br>As expert Robin Hanson puts it 👇 <a href="https://t.co/3j5OzSTPkq">pic.twitter.com/3j5OzSTPkq</a></p>&mdash; Tyler DurdΞth (@tylerdurdeth) <a href="https://twitter.com/tylerdurdeth/status/1875887690857804115?ref_src=twsrc%5Etfw">January 5, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">… While, before, trad media had to resort to Polymarket screenshots, Myriad will now embed this “alternative source of truth” directly into the news! Incredibly powerful and disruptive for the media sector, providing unparalleled insight and perspective to consumers of news.</p>&mdash; Tyler DurdΞth (@tylerdurdeth) <a href="https://twitter.com/tylerdurdeth/status/1875887695316340863?ref_src=twsrc%5Etfw">January 5, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">In short, never underestimate a David taking on a Goliath, especially in an emerging sector, and especially when the Goliath in question is in the crosshairs of regulators. Myriad’s future is very bright indeed, as is the future of its sister companies.<br><br>Billions will predict! <a href="https://t.co/tENHctwnAm">pic.twitter.com/tENHctwnAm</a></p>&mdash; Tyler DurdΞth (@tylerdurdeth) <a href="https://twitter.com/tylerdurdeth/status/1875887723816640580?ref_src=twsrc%5Etfw">January 5, 2025</a></blockquote>`,
    `<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">If you wonder how to financially position for the media revolution, have a look at the thread below <a href="https://t.co/0KQelFdEs8">https://t.co/0KQelFdEs8</a></p>&mdash; Tyler DurdΞth (@tylerdurdeth) <a href="https://twitter.com/tylerdurdeth/status/1875887727822114990?ref_src=twsrc%5Etfw">January 5, 2025</a></blockquote>`
  ] as const,
] as const;

const TwitterThreadsGrid = memo(() => {
  return (
    <div className="py-12 bg-black">
      <div className="container mx-auto px-4 max-w-7xl">
        <div className="text-center mb-8">
          <h2 className="text-4xl font-bold text-white mb-4">Still On The Fence? Read on</h2>
          <p className="text-lg text-gray-300">
            threads by{" "}
            <TwitterAuthorLink handle="tylerdurdeth" url="https://x.com/tylerdurdeth" />{" "}
            <TwitterAuthorLink handle="vincevanbtc" url="https://x.com/vincevanbtc" />
          </p>
        </div>
        
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* First column with scrollable thread */}
          <TwitterThreadColumn tweets={threadsGrid[0]} />

          {/* Second column with thread */}
          <TwitterThreadColumn tweets={threadsGrid[1]} />
        </div>
      </div>
    </div>
  );
});

TwitterThreadsGrid.displayName = 'TwitterThreadsGrid';

export default TwitterThreadsGrid;
